name: Finca Monticello
title: Finca Monticello
description: Finca Monticello
url: https://fincacermeno.com
logo: "ico"

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty
